# Blood donation analysis - Udemy

https://www.udemy.com/course/data-science-in-healthcare/

In [91]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

In [84]:
train = pd.read_csv('C:/Users/joeba/OneDrive/Documents/ML/blood donation analysis/blood-train.csv')
test = pd.read_csv('C:/Users/joeba/OneDrive/Documents/ML/blood donation analysis/blood-test.csv')

In [85]:
print('Train:{}, test:{}'.format(train.shape, test.shape))

Train:(576, 6), test:(200, 5)


In [86]:
y = train['Made Donation in March 2007']
X = train.drop(['Unnamed: 0', 'Made Donation in March 2007'], axis=1)
test = test.drop('Unnamed: 0', axis=1)

In [87]:
X.describe()

Months since Last Donation  Number of Donations  \
count                  576.000000           576.000000   
mean                     9.439236             5.427083   
std                      8.175454             5.740010   
min                      0.000000             1.000000   
25%                      2.000000             2.000000   
50%                      7.000000             4.000000   
75%                     14.000000             7.000000   
max                     74.000000            50.000000   

       Total Volume Donated (c.c.)  Months since First Donation  
count                   576.000000                   576.000000  
mean                   1356.770833                    34.050347  
std                    1435.002556                    24.227672  
min                     250.000000                     2.000000  
25%                     500.000000                    16.000000  
50%                    1000.000000                    28.000000  
75%                    1750.000000                    49.250000  
max                   12500.000000                    98.000000

In [88]:
test.describe()

Months since Last Donation  Number of Donations  \
count                   200.00000           200.000000   
mean                      9.49500             5.935000   
std                       7.61907             6.125224   
min                       0.00000             1.000000   
25%                       4.00000             2.000000   
50%                       7.00000             4.000000   
75%                      14.00000             8.000000   
max                      40.00000            41.000000   

       Total Volume Donated (c.c.)  Months since First Donation  
count                   200.000000                   200.000000  
mean                   1483.750000                    35.475000  
std                    1531.305955                    25.111197  
min                     250.000000                     2.000000  
25%                     500.000000                    14.000000  
50%                    1000.000000                    31.000000  
75%                    2000.000000                    52.000000  
max                   10250.000000                    98.000000

In [89]:
X.columns

Index(['Months since Last Donation', 'Number of Donations',
       'Total Volume Donated (c.c.)', 'Months since First Donation'],
      dtype='object')

In [90]:
X = X.drop(['Total Volume Donated (c.c.)'], axis=1)
X

Months since Last Donation  Number of Donations  \
0                             2                   50   
1                             0                   13   
2                             1                   16   
3                             2                   20   
4                             1                   24   
..                          ...                  ...   
571                          23                    1   
572                          16                    3   
573                          21                    2   
574                          39                    1   
575                          72                    1   

     Months since First Donation  
0                             98  
1                             28  
2                             35  
3                             45  
4                             77  
..                           ...  
571                           23  
572                           86  
573                           52  
574                           39  
575                           72  

[576 rows x 3 columns]

In [92]:
ss = StandardScaler()
X = ss.fit_transform(X)

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [94]:
lr = LogisticRegression(random_state=1223)
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1223, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [95]:
y_pred = lr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

0.75
0.5857142857142857


In [96]:
svmc = SVC(probability=True)
svmc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [97]:
y_pred = svmc.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

0.7068965517241379
[[80  1]
 [33  2]]
0.5223985890652557


In [98]:
rf = RandomForestClassifier(n_estimators=25)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [99]:
y_pred = rf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

0.7413793103448276
[[71 10]
 [20 15]]
0.652557319223986


In [100]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [101]:
y_pred = dt.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

0.646551724137931
[[67 14]
 [27  8]]
0.5278659611992945


In [102]:
ann = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(25,), random_state=1223)
ann.fit(X_train, y_train)

C:\Users\joeba\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(25,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1223, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [103]:
y_pred = ann.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

0.7327586206896551
[[72  9]
 [22 13]]
0.6301587301587301
